language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test:ci
  - npm run build

after_success:
  # - npm run coverage

branches:
  only:
    - master
