const ActionTypes = {
  ZOOM: 'ZOOM',
  ZOOM_IN_START: 'ZOOM_IN_START',
  ZOOM_IN: 'ZOOM_IN',
  ZOOM_OUT_START: 'ZOOM_OUT_START',
  ZOOM_OUT: 'ZOOM_OUT',
  ZOOM_RESET: 'ZOOM_RESET',
  MOVE_START: 'MOVE_START',
  MOVE_END: 'MOVE_END',
  MOVE_DRAG_START: 'MOVE_DRAG_START',
  MOVE_DRAG: 'MOVE_DRAG',
  MOVE_DRAG_END: 'MOVE_DRAG_END',
  RESET: 'RESET',
  PERFORM_ACTION_START: 'PERFORM_ACTION_START',
  PERFORM_ACTION_END: 'PERFORM_ACTION_END',
  TOGGLE_GUIDES: 'TOGGLE_GUIDES',
  TOGGLE_BOX_INSPECTOR: 'TOGGLE_BOX_INSPECTOR',
}

export default ActionTypes
