const ActionTypes = {
  // General
  PERFORM_ACTION_START: 'PERFORM_ACTION_START',
  PERFORM_ACTION_END: 'PERFORM_ACTION_END',
  RESET: 'RESET',

  // Zoom
  ZOOM: 'ZOOM',
  ZOOM_IN_START: 'ZOOM_IN_START',
  ZOOM_IN: 'ZOOM_IN',
  ZOOM_OUT_START: 'ZOOM_OUT_START',
  ZOOM_OUT: 'ZOOM_OUT',
  ZOOM_RESET: 'ZOOM_RESET',

  // Moving
  MOVE_START: 'MOVE_START',
  MOVE_END: 'MOVE_END',
  MOVE_DRAG_START: 'MOVE_DRAG_START',
  MOVE_DRAG: 'MOVE_DRAG',
  MOVE_DRAG_END: 'MOVE_DRAG_END',

  // Resizing
  RESIZE_ARTBOARD: 'RESIZE_ARTBOARD',

  // Toolbar
  TOGGLE_GUIDES: 'TOGGLE_GUIDES',
  TOGGLE_BOX_INSPECTOR: 'TOGGLE_BOX_INSPECTOR',

  EYEDROPPER_START: 'EYEDROPPER_START',
  EYEDROPPER_READY: 'EYEDROPPER_READY',
  EYEDROPPER_STOP: 'EYEDROPPER_STOP',
}

export default ActionTypes
